{{- $releaseName := .Release.Name -}}
{{- $tracingUrl := include "qgis-server.tracingUrl" . -}}
{{- $metricsUrl := include "qgis-server.metricsUrl" . -}}
{{- $serverProto := ternary "https" "http" .Values.s3.awsHttps -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-configmap
  labels:
{{- include "qgis-server.labels" . | nindent 4 }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{ if .Values.caSecretName }}
  NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
  {{ end }}
  AWS_PAGER: ""
  AWS_CA_BUNDLE: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
  AWS_ENDPOINT_URL: {{ printf "%s://%s:%d" $serverProto .Values.s3.server (.Values.s3.serverPort | int) | quote }}
  AWS_REGION: {{ quote .Values.s3.awsRegion }}
  AWS_HTTPS: {{ quote .Values.s3.awsHttps }}
  AWS_S3_ENDPOINT: {{ printf "%s:%d" .Values.s3.server (.Values.s3.serverPort | int) | quote }}
  AWS_VIRTUAL_HOSTING: {{ quote .Values.s3.awsVirtualHosting }}
  AWS_BUCKET_NAME: {{ quote .Values.s3.bucketName }}
  SSL_CERT_FILE: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
  # GDAL_HTTP_UNSAFESSL: {{ quote .Values.s3.gdalHttpUnsafessl }}
  QGIS_SERVER_LOG_FILE: {{ quote .Values.env.qgisServerLogFile }}
  QGIS_SERVER_LOG_LEVEL: {{ quote .Values.env.qgisServerLogLevel }}
  RAW_DATA_PROXY_URL: {{ quote .Values.env.rawDataProxyUrl }}
  POLLING_INTERVAL: {{ quote .Values.env.pollingInterval }}
  {{ if .Values.env.productTypes }}
  PRODUCT_TYPES: {{ quote .Values.env.productTypes }}
  {{ end }}
{{- end }}
