{{- $chartName := include "qgis-server.name" . -}}
{{- $tracingUrl := include "qgis-server.tracingUrl" . -}}
{{- $metricsUrl := include "qgis-server.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{ if .Values.caSecretName }}
  NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
  {{ end }}
  AWS_ACCESS_KEY_ID: {{ quote .Values.s3.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ quote .Values.s3.secretAccessKey }}
  AWS_ENDPOINT_URL: {{ quote .Values.s3.endpointUrl }}
  AWS_BUCKET_NAME: {{ quote .Values.s3.bucketName }}
  QGIS_SERVER_LOG_FILE: {{ quote .Values.env.qgisServerLogFile }}
  QGIS_SERVER_LOG_LEVEL: {{ quote .Values.env.qgisServerLogLevel }}
  RAW_DATA_PROXY_URL: {{ quote .Values.env.rawDataProxyUrl }}
  POLLING_INTERVAL: {{ quote .Values.env.pollingInterval }}
{{- end }}
