{{- $releaseName := .Release.Name -}}
{{- $chartName := include "qgis-server.name" . -}}
{{- $cloudProviderFlavor := include "qgis-server.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "qgis-server.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "qgis-server.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "qgis-server.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "qgis-server.environment" . }}
    release: {{ $releaseName }}
    {{- include "qgis-server.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "qgis-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "qgis-server.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-sidecar-deployment
          {{- with .Values.sidecar }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.cloudProvider.imagePullPolicy }}
          # For debugging uncomment the following lines
          # command:
          #   - sleep
          #   - infinity
          {{- if .Values.sidecar.resources.enabled }}
          resources:
            {{- toYaml .Values.sidecar.resources.value | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "qgis-server.secretName" . }}
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          volumeMounts:
            - name: qgis-storage
              mountPath: /io/data
              subPath: data
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          imagePullPolicy: {{ .Values.cloudProvider.imagePullPolicy }}
          # For debugging uncomment the following lines
          # command:
          #   - sleep
          #   - infinity
          volumeMounts:
            {{- if .Values.caSecretName }}
            - name: root-ca
              mountPath: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
              subPath: {{ quote .Values.caKey }}
            {{- end }}
            {{- if .Values.fs.sourcePvc.enabled  }}
            - name: qgis-storage
              mountPath: /io/data
              subPath: data
            - name: qgis-storage
              mountPath: /io/plugins
              subPath: plugins
            - name: qgis-storage
              mountPath: /usr/share/fonts
              subPath: fonts
            - name: proxy-mount
              mountPath: /etc/nginx
            {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
          envFrom:
            - secretRef:
                name: {{ template "qgis-server.secretName" . }}
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.targetPort }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.caSecretName }}
        - name: root-ca
          secret:
            secretName: {{ .Values.caSecretName }}
        {{- end }}
        {{- if .Values.fs.sourcePvc.enabled }}
        - name: qgis-storage
          # Empty in-memory volume when no pvc
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: {{ quote .Values.fs.sourcePvc.name }}
        {{- end }}
        - name: proxy-mount
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-proxy-configmap
{{- end -}}
