{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-{{ $chartName }}-proxy-configmap
  labels:
{{- include "qgis-server.labels" . | nindent 4 }}
data:
  nginx.conf: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
{{- end }}
