{{- $releaseName := .Release.Name -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-proxy-configmap
  labels:
{{- include "qgis-server.labels" . | nindent 4 }}
data:
  log_format.conf: {{ tpl (.Files.Get "config/log_format.conf") . | quote }}
  fastcgi_params: {{ tpl (.Files.Get "config/fastcgi_params") . | quote }}
  mime.types: {{ .Files.Get "config/mime.types" | quote }}
  nginx.conf: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
{{- end }}
