{{- $releaseName := .Release.Name -}}
{{- $chartName := include "qgis-server.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-proxy-configmap
  labels:
{{- include "qgis-server.labels" . | nindent 4 }}
data:
  mime.types: {{ .Files.Get "config/mime.types" | quote }}
  nginx.conf: {{ tpl (.Files.Get "config/nginx.conf") . | quote }}
{{- end }}
