{{- $cloudProviderFlavor := include "qgis-server.cloudProviderFlavor" . -}}
{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "qgis-server.name" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  path: {{ .Values.route.path | default "/" }}
  to:
    kind: Service
    name: {{ $releaseName }}-{{ $chartName }}
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: edge
    {{- if .Values.route.tls.useCert }}
    certificate: {{ .Values.route.tls.certificate | quote }}
    key: {{ .Values.route.tls.key | quote }}
    caCertificate: {{ .Values.route.tls.caCertificate | quote }}
    insecureEdgeTerminationPolicy: Redirect
    {{- end }}
  {{- end }}
{{- end -}}
