apiVersion: v1
kind: Secret
metadata:
  name: {{ template "qgis-server.secretName" . }}
  labels:
{{- include "qgis-server.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc | quote }}