global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: integration
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
annotations: {}

cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  imagePullSecretName: acr-registry
  imagePullPolicy: Always
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

fs:
  sourcePvc:
    enabled: true
    name: dem-pvc-int

s3:
  accessKeyId: raster
  secretAccessKey: rasterPassword
  endpointUrl: http://10.8.0.9:9000
  bucketName: dem-int

sidecar:
  repository: qgis-server-sidecar
  tag: v1.0.5
  resources:
    enabled: true
    value:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 1Gi

image:
  repository: qgis-server
  tag: v0.1.0

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  qgisServerLogFile: /var/tmp/qgisserver.log
  qgisServerLogLevel: 1
  rawDataProxyUrl: http://dem-int-proxy-production-nginx-s3-gateway
  pollingInterval: 300000
  productTypes:

resources:
  enabled: true
  value:
    limits:
      cpu: 200m
      memory: 4Gi
    requests:
      cpu: 50m
      memory: 4Gi

route:
  enabled: true
  path: /
  https: true
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  type: 'nginx-kubernetes' # supported values: 'nginx-org' | 'nginx-kubernetes'
  host: localhost
  path: /
  cors:
    enabled: true
    origin: '*'
